# Generated by Django 4.2.4 on 2023-09-10 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('nome_contratante', models.CharField(max_length=100, verbose_name='Nome do contratante')),
                ('cpf_contratante', models.CharField(max_length=100, verbose_name='CPF do contratante')),
                ('rua_contratante', models.CharField(max_length=100, verbose_name='Rua do contratante')),
                ('numero_contratante', models.CharField(max_length=100, verbose_name='Número do contratante')),
                ('cidade_contratante', models.CharField(max_length=100, verbose_name='Cidade do contratante')),
                ('estado_contratante', models.CharField(max_length=100, verbose_name='Estado do contratante')),
                ('salao', models.CharField(max_length=100, verbose_name='Salão')),
                ('evento', models.CharField(max_length=100, verbose_name='Tipo do Evento')),
                ('qtd_convidados', models.IntegerField(max_length=10, verbose_name='Quantidade de convidados')),
                ('data_evento', models.CharField(max_length=100, verbose_name='Data do Evento')),
                ('qtd_garcons', models.IntegerField(max_length=10, verbose_name='Quantidade de garçons')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Aluguel')),
                ('valor_buffet', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Buffet')),
                ('data_pagar', models.DateTimeField(verbose_name='Data a pagar')),
                ('data_contrato', models.DateTimeField(default=datetime.date.today, verbose_name='Data do contrato')),
            ],
            options={
                'verbose_name': 'Contratos',
            },
        ),
    ]
