# Generated by Django 4.2.4 on 2023-09-10 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Contrato'},
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_contrato',
            field=models.DateField(default=datetime.date.today, verbose_name='Data do contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_evento',
            field=models.DateField(max_length=100, verbose_name='Data do Evento'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_pagar',
            field=models.DateField(verbose_name='Data a pagar'),
        ),
    ]
