# Generated by Django 4.2.4 on 2023-09-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contrato_options_alter_contrato_data_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='numero_contratante',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número da rua do contratante'),
        ),
    ]
